### PR TITLE
Moved include tag to String Literal

### LINKED ISSUE #31: Include tag proper template names
In `Shopify/liquid` the syntax for the include tag is different from my implementation.

```
  # Simply include another template:
  #
  #   {% include 'product' %}
  #
  # Include a template with a local variable:
  #
  #   {% include 'product' with products[0] %}
  #
```

- [x] With String literal
- [ ] With variable

We should implement the Include tag similar. This issue is to keep track.

### PR DESCRIPTION
**Pull request by LucioFranco**
Fixes #31. Still need to figure out variable part and if we want to include it.

### CODE REVIEW

**Comment by johannhof** [comment]
:+1: , but why can't we have both, for flexibility?

**Comment by LucioFranco** [comment]
@johannhof What do you mean by both?

**Comment by johannhof** [comment]
We could support both identifiers and string literals for specifying the path, or is that weird because it's actually a variable?

**Comment by LucioFranco** [comment]
I don't think we should do it because a identifier is a variable usually. Maybe we could add a nice error message when a user tries an identifier and they meant a String Literal.

**Comment by johannhof** [comment]
That sounds nice, wanna make a good-first-bug for it?

**Pull request merged**
