### PR TITLE
Add most of the remaining math filters

### PR DESCRIPTION
**Pull request by bfrog**
* times
* divided_by
* ceil
* floor
* round

### CODE REVIEW

**Comment by johannhof** [comment]
Hey, thanks for contributing! Your PR is looking good, just two minor things:

- you'll have to rebase on master, sorry for that :)
- I'd love if you could add assertions for the error returning paths as well, doesn't have to be fancy (e.g. call "ceil" with a string and check it returns an error)

Thank you!

**Comment by bfrog** [comment]
I spent few thinking about a way to make a macro for testing error returns without adding a bunch of fluff, might take me awhile. This was rebased otherwise though with the success cases tested so far.

**Comment by johannhof** [comment]
Can't you just do 
```rust
assert!(ceil(Bool(true), &[]).is_err());
```
? :)

**Comment by bfrog** [comment]
Right, I was for whatever reason thinking testing the error type and string would also be good, but I guess just showing its an error scenario would be good enough

**Comment by johannhof** [comment]
Great job, thank you! :+1:

**Pull request merged**
